client_layout :-
  writeln("\n************************************************************************************************************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                       CCCCC    L        III   EEEEE   N    N   TTTTTT   EEEEE                                                        *"),
  writeln("*                                                       C        L         I    E       NN   N     TT     E                                                            *"),
  writeln("*                                                       C        L         I    EEEE    N N  N     TT     EEEE                                                         *"),
  writeln("*                                                       C        L         I    E       N  N N     TT     E                                                            *"),
  writeln("*                                                       CCCCC    LLLLLL   III   EEEEE   N   NN     TT     EEEEE                                                        *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                         Menu de Clientes                                                                             *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("------------------------------------------------------------------------------------------------------------------------------------------------------------------------"),
  writeln("*********************************************************************** Gerencie os Clientes ***************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                               📝 1. Cadastrar um novo cliente                                                                        *"),
  writeln("*                                                               🔍 2. Buscar um cliente por CPF                                                                        *"),
  writeln("*                                                               📜 3. Buscar todos os clientes                                                                         *"),
  writeln("*                                                               ✏️ 4. Atualizar um cliente                                                                             *"),
  writeln("*                                                               🗑️ 5. Deletar um cliente                                                                               *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                               ❌ 0 <- Voltar ao Menu Principal                                                                       *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("************************************************************************************************************************************************************************").
