menu_layout :- 
  writeln("\n************************************************************************************************************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                          PPPPP   H     H    AAAAA    RRRRR     M     M     AAAAA    L         OOOO    GGGGG                                          *"),
  writeln("*                                          P    P  H     H   A     A   R    R   M M   M M   A     A   L        O    O  G                                               *"),
  writeln("*                                          PPPPP   HHHHHHH   AAAAAAA   RRRRR    M  M M  M   AAAAAAA   L        O    O  G   GGG                                         *"),
  writeln("*                                          P       H     H   A     A   R   R    M   M   M   A     A   L        O    O  G    G                                          *"),
  writeln("*                                          P       H     H   A     A   R    R   M       M   A     A   LLLLLLL   OOOO    GGGGG                                          *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                    Pharmalog - Gestão de Farmácia                                                                    *"),
  writeln("*                                                                          Versão 1.0 (PROLOG)                                                                         *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("------------------------------------------------------------------------------------------------------------------------------------------------------------------------"),
  writeln("******************************************************************** Bem-Vindo ao Sistema Pharmalog ********************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                         🌟 1. Usuários                                                                               *"),
  writeln("*                                                                         📦 2. Produtos                                                                               *"),
  writeln("*                                                                         💰 3. Vendas                                                                                 *"),
  writeln("*                                                                         👥 4. Clientes                                                                               *"),
  writeln("*                                                                         💬 5. Chat                                                                                   *"),
  writeln("*                                                                         📊 6. Relatórios de Produtos                                                                 *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                         ❌ 0 <- Sair                                                                                 *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("************************************************************************************************************************************************************************").

