product_layout :-
  writeln("\n************************************************************************************************************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                   PPPPP   RRRRR    OOOO   DDDDD    U    U  TTTTTT   OOOO    SSSSS                                                    *"),
  writeln("*                                                   P    P  R    R  O    O  D    D   U    U    TT    O    O  S                                                         *"),
  writeln("*                                                   PPPPP   RRRRR   O    O  D    D   U    U    TT    O    O   SSSSS                                                    *"),
  writeln("*                                                   P       R   R   O    O  D    D   U    U    TT    O    O        S                                                   *"),
  writeln("*                                                   P       R    R   OOOO   DDDDD     UUUU     TT     OOOO    SSSSS                                                    *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                        Menu de Produtos                                                                              *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("------------------------------------------------------------------------------------------------------------------------------------------------------------------------"),
  writeln("*********************************************************************** Gerencie os Produtos ***************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                               📦 1. Cadastrar um novo produto                                                                        *"),
  writeln("*                                                               🔍 2. Buscar um produto por ID                                                                         *"),
  writeln("*                                                               📝 3. Buscar um produto por nome                                                                       *"),
  writeln("*                                                               📜 4. Buscar todos os produtos                                                                         *"),
  writeln("*                                                               ✏️ 5. Atualizar um produto                                                                             *"),
  writeln("*                                                               🗑️ 6. Remover um produto                                                                               *"),
  writeln("*                                                               ⚠️ 7. Alertar sobre Baixo Estoque                                                                      *"),
  writeln("*                                                               ⏳ 8. Alertar sobre Produtos Perto de Vencer                                                           *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                               ❌ 0 <- Voltar ao Menu Principal                                                                       *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("************************************************************************************************************************************************************************").
