report_layout :-
  writeln("\n************************************************************************************************************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                               RRRRR    EEEEE   L        AAAAA   TTTTTT   OOOO   RRRRR   III   OOOO    SSSSS                                          *"),
  writeln("*                                               R    R   E       L       A     A    TT    O    O  R    R   I   O    O  S                                               *"),
  writeln("*                                               RRRRR    EEEE    L       AAAAAAA    TT    O    O  RRRRR    I   O    O   SSSSS                                          *"),
  writeln("*                                               R   R    E       L       A     A    TT    O    O  R   R    I   O    O        S                                         *"),
  writeln("*                                               R    R   EEEEE   LLLLLL  A     A    TT     OOOO   R    R  III    OOOO    SSSSS                                         *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                         Menu de Relatórios                                                                           *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("------------------------------------------------------------------------------------------------------------------------------------------------------------------------"),
  writeln("*********************************************************************** Gerencie os Relatórios *************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                 📊 1. Relatório por faixa de preço                                                                   *"),
  writeln("*                                                                 📋 2. Relatório por categoria                                                                        *"),
  writeln("*                                                                 📦 3. Relatório por faixa de estoque                                                                 *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                 ❌ 0 <- Voltar ao Menu Principal                                                                     *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("************************************************************************************************************************************************************************").
