sales_layout :-
  writeln("\n************************************************************************************************************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                         V     V  EEEEE   N    N  DDDDD    AAAAA   SSSSS                                                              *"),
  writeln("*                                                         V     V  E       NN   N  D    D  A     A  S                                                                  *"),
  writeln("*                                                          V   V   EEEE    N N  N  D    D  AAAAAAA   SSSSS                                                             *"),
  writeln("*                                                           V V    E       N  N N  D    D  A     A       S                                                             *"),
  writeln("*                                                            V     EEEEE   N   NN  DDDDD   A     A  SSSSS                                                              *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                         Menu de Vendas                                                                               *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("------------------------------------------------------------------------------------------------------------------------------------------------------------------------"),
  writeln("*********************************************************************** Gerencie as Vendas *****************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                               💵 1. Cadastrar uma nova venda                                                                         *"),
  writeln("*                                                               🔍 2. Buscar um cliente por CPF                                                                        *"),
  writeln("*                                                               📜 3. Buscar todas as vendas                                                                           *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                               ❌ 0 <- Voltar ao Menu Principal                                                                       *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("************************************************************************************************************************************************************************").

