user_layout :-
  writeln("\n************************************************************************************************************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                    U    U   SSSSS   UUU   U   AAAAA    RRRRR     III    OOOO    SSSSS                                                *"),
  writeln("*                                                    U    U   S        U    U  A     A   R    R     I    O    O  S                                                     *"),
  writeln("*                                                    U    U    SSSSS   U    U  AAAAAAA   RRRRR      I    O    O   SSSSS                                                *"),
  writeln("*                                                    U    U         S  U    U  A     A   R   R      I    O    O        S                                               *"),
  writeln("*                                                     UUUU    SSSSSS    UUUU   A     A   R    R    III    OOOO    SSSSS                                                *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                        Menu de Usuários                                                                              *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("------------------------------------------------------------------------------------------------------------------------------------------------------------------------"),
  writeln("*********************************************************************** Gerencie os Usuários ***************************************************************************"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                               👤 1. Cadastrar um novo usuário                                                                        *"),
  writeln("*                                                               🔍 2. Buscar um usuário por CPF                                                                        *"),
  writeln("*                                                               📜 3. Listar todos os usuários                                                                         *"),
  writeln("*                                                               ✏️ 4. Atualizar um usuário                                                                             *"),
  writeln("*                                                               🗑️ 5. Deletar um usuário                                                                               *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                               ❌ 0 <- Voltar ao Menu Principal                                                                       *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("*                                                                                                                                                                      *"),
  writeln("************************************************************************************************************************************************************************").
